### ISSUE TITLE
multi-Client example/functionality 

### ISSUE THREAD

**Issue by SamuelWeeks** [MattTuttle/hxnet#4]
Been using this since you have recently updated the examples. even though this is alpha code, the telnet server works pretty good.  would it be possible to add in multi-Client support? or if it is already possible an example?

**Comment by MattTuttle** [comment]
By multi-client do you mean a server that can handle multiple clients? That is already handle via factories. Every connection creates a new protocol instance that communicates with each individual client.

**Comment by SamuelWeeks** [comment]
After reviewing the source code I managed to figure out a few things, I guess what I'm really looking for are some simple examples to do things.  A couple things I can't seem to figure out(on the telnet examples, I can't get the others to work write yet)
- how to writelne to a single client, instead of broadcasting to all
- how in the server side to detect when I client has connected. (On connect only seems to work on the client side)
- how to make the server not crash when a single client disconnectes.

I do understand that this is still very early code, so not everything is implemented, and I would like to help out if you are open to pull request.
